[package]
name = "simflash"
version = "0.1.0"
authors = ["David Brown <david.brown@linaro.org>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
failure_derive = "0.1.5"
rand = "0.4.5"
log = "0.4"
